package com.kt.api;

public class KTOpenApiId {
	public static String CLICK_2_CALL_MAKE = "2.0.SANDBOX.CALL.CLICK2CALL.MAKE"; //
	public static String CLICK_2_CALL_QUERY_RESULT = "2.0.SANDBOX.CALL.CLICK2CALL.QUERYRESULT"; //
	public static String CID_SET_NOTI = "2.0.SANDBOX.CALL.CID.SETNOTI"; //
	public static String SMS_MAKE = "2.0.SANDBOX.SMS.MAKE"; //
	public static String SMS_QUERY_RESULT = "2.0.SANDBOX.SMS.QUERYRESULT"; //

	public static String VOICE_CONFERENCE_MAKE = "2.0.SANDBOX.CALL.VOICECONFERENCE.MAKE";
	public static String VOICE_CONFERENCE_MODIFY_MEMBER = "2.0.SANDBOX.CALL.VOICECONFERENCE.MODIFYMEMBER";
	public static String VOICE_CONFERENCE_QUERY_MEMBER = "2.0.SANDBOX.CALL.VOICECONFERENCE.QUERYMEMBER";
	public static String CID_UNSET_NOTI = "2.0.SANDBOX.CALL.CID.UNSETNOTI";
	public static String CID_GET_NOTI_INFO = "2.0.SANDBOX.CALL.CID.GETNOTIINFO";
	public static String SMS_MAKE_WITH_CHECK = "2.0.SANDBOX.SMS.MAKEWITHCHECK";
	public static String SMS_REGIST = "2.0.SANDBOX.SMS.REGIST";
	public static String SMS_UNREGIST = "2.0.SANDBOX.SMS.UNREGIST";
	public static String SMS_QUERY_REGIST = "2.0.SANDBOX.SMS.QUERYREGIST";
}
